### ISSUE TITLE
MDNS component not found after changes in IDF 5.0 (MEGH-3638)

### ISSUE THREAD

**Issue by espzav** [espressif/esp-rainmaker#133]
Please, we are using esp_rainmaker component in esp-bsp example project and this failing now, because they are changes in mdns compnent in IDF 5.0. The mdns component is moved to component manager. Please, could you help me with fix?

Thank you very much.

**Comment by shahpiyushv** [comment]
@espzav Can you please create a file at location `components/esp_rainmaker/idf_component.yml` with this content:

```
## IDF Component Manager Manifest File
dependencies:
  espressif/mdns:
    version: "^1.0.3"
    rules:
      - if: "idf_version >=5.0"
```

Please note that release/v5.0 branch is still not stable and so it may have other breaking changes in future.
